### ISSUE TITLE
Data breach on app exposes passwords

### ISSUE THREAD

**Issue by emmapaczkowski** [googleinterns/step124-2020#25]
![Screenshot 2020-07-09 at 10 19 44 AM](https://user-images.githubusercontent.com/45154853/87068978-a80e6f80-c1d3-11ea-935f-32bcaf146830.png)

**Comment by emmapaczkowski** [comment]
I think it may have to do with the read/write permissions of the database.

**Comment by andy7809** [comment]
What's the progress on this one?

**Comment by emmapaczkowski** [comment]
Since no one in our initial round of user feedback said anything about this and I am unable to find anything explaining why this is happening I am going to close this issue.
