### ISSUE TITLE
Signup and Log in cards expand the whole screen

### ISSUE THREAD

**Issue by emmapaczkowski** [googleinterns/step124-2020#37]
Not too sure what happened but the cards where you sign up and log in now expand the whole screen (in master ).

**Comment by emmapaczkowski** [comment]
@andy7809 If you want I am happy to take a look at it but  I thought you may have a better idea of what is going on.

**Comment by andy7809** [comment]
I'm afk right now, I'll investigate this before our sync

**Comment by andy7809** [comment]
Didn't mean to close. This is a front end css issue, I am going to fix on my dev branch. Is reproduced on master. Here are steps:

1. Serve index
2. Navigate to signup.html or login.html

On both pages, the containing cards stretch to the width of the screen, instead of being centered and fit.

**Comment by andy7809** [comment]
Closed with f539d66
