### ISSUE TITLE
Login / sign in redirect to index

### ISSUE THREAD

**Issue by andy7809** [googleinterns/step124-2020#44]
Submitting login or signin forms should send the user back to the index page.

**Comment by andy7809** [comment]
Does signin already do this?

**Comment by PriyaVarra** [comment]
pull request #46 should hopefully address this

**Comment by andy7809** [comment]
I second that #46 addresses this, let me re-tag and set to close on merge.

**Comment by andy7809** [comment]
Ope you already did that, great!
