### ISSUE TITLE
When you turn off saved places all places are cleared

### ISSUE THREAD

**Issue by emmapaczkowski** [googleinterns/step124-2020#77]

**Comment by PriyaVarra** [comment]
I think this might be fixed now. Please feel free to confirm!

**Comment by andy7809** [comment]
I agree, can't reproduce this one on my new account. Probably related to #80, I'll let you close this if you agree @emmapaczkowski

**Comment by emmapaczkowski** [comment]
You two are right.  I am no longer getting the issue
