### ISSUE TITLE
Saved places toggle throwingh an error

### ISSUE THREAD

**Issue by emmapaczkowski** [googleinterns/step124-2020#80]
Not too sure what is going on.  I will look at this tomorrow.

**Comment by andy7809** [comment]
Could we get some help on this one @PriyaVarra ?

**Comment by andy7809** [comment]
I opened #81 to address this

**Comment by andy7809** [comment]
In my account, I have 5 saved places. For some reason, 3 of the saved places lat/lng is stored as a string, and the other two are numbers. The change I pushed does show the cards, but for each of the places with strings as lat/lng, the following error is shown on the terminal: `InvalidValueError: setPosition: not a LatLng or LatLngLiteral: in property lat: not a number`

**Comment by PriyaVarra** [comment]
I believe the code in master now accounts for this. I think its because when we pass in places objects from firebase, we have to store lat/lng as floats but from the place api they are actually functions that return floats so I have added a check for this.

**Comment by PriyaVarra** [comment]
I tried to check that the code on master was working last night but I would not be surprised at all if I missed some stuff. Would you and Emma be willing to double check that the issues are addressed from the code on master now?

**Comment by andy7809** [comment]
Yes, I'm doing some testing this morning and I will be sure that these issues are addressed

**Comment by PriyaVarra** [comment]
It's possible that some of the older entries under an account before the changes may no longer be compatible. Do you know how to access firebase internally and remove these entries? I just created a new account to test in the meantime..

**Comment by andy7809** [comment]
Oh that's a good idea, I bet it does have to do with older versions. The issue is when we populate the pins with strings in the lat/lng, we get the InvalidValueError. We also get errors when we try to call the function .lat() on the string value.

**Comment by andy7809** [comment]
Looks like it works for new accounts. Maybe we need to migrate the old firebase accounts? :P

**Comment by PriyaVarra** [comment]
@emmapaczkowski  Do you have the ability to clear the entries in the old accounts in firebase?
