### ISSUE TITLE
Toggling between trip on/off doesn't show saved places

### ISSUE THREAD

**Issue by andy7809** [googleinterns/step124-2020#92]
Steps to reproduce:
1. Login
2. Toggle on show saved places
3. Create a new trip, add a few saved places
4. toggle trip on
5. toggle trip off

Only the pins for the trip are displayed, not all pins. I think we missed a call to display saved places somewhere?

**Comment by PriyaVarra** [comment]
Thanks for finding that! I have pushed a new change to TripsFeature that I think fixes this. Let me know if you still have the issue!
